RuntimeError: some more work towards compatibility of libfnord
RAISE_FAKE() is basically libfnord's RAISE(), but since that
one is misleading, I've done it that way.